name: Generate SDK from OpenAPI

on:
  schedule:
    # Run daily at UTC 00:00 (JST 09:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # For manual execution

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Download OpenAPI specs
        run: |
          mkdir -p tmp
          curl -o tmp/openapi-v1.json https://docs.growi.org/openapi-spec-apiv1.json
          curl -o tmp/openapi-v3.json https://docs.growi.org/openapi-spec-apiv3.json

      - name: Check for changes in OpenAPI specs
        id: check_changes
        run: |
          # Check for differences if previous specs exist
          if [ -f .openapi-cache/openapi-v1.json ] && [ -f .openapi-cache/openapi-v3.json ]; then
            DIFF_V1=$(diff tmp/openapi-v1.json .openapi-cache/openapi-v1.json || true)
            DIFF_V3=$(diff tmp/openapi-v3.json .openapi-cache/openapi-v3.json || true)
            if [ -z "$DIFF_V1" ] && [ -z "$DIFF_V3" ]; then
              echo "No changes in OpenAPI specs"
              echo "has_changes=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
          echo "has_changes=true" >> $GITHUB_OUTPUT
          mkdir -p .openapi-cache
          cp tmp/openapi-v1.json .openapi-cache/
          cp tmp/openapi-v3.json .openapi-cache/

      - name: Setup Node.js
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v2
        if: steps.check_changes.outputs.has_changes == 'true'
        with:
          version: 8

      - name: Install dependencies
        if: steps.check_changes.outputs.has_changes == 'true'
        run: pnpm install

      - name: Generate SDK
        if: steps.check_changes.outputs.has_changes == 'true'
        run: pnpm run generate:api

      - name: Format generated code
        if: steps.check_changes.outputs.has_changes == 'true'
        run: pnpm exec biome format --write ./src/generated

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'feat(sdk): update generated SDK code'
          title: '⚡️ Update SDK from latest OpenAPI specs'
          body: |
            Updated SDK code based on OpenAPI specification updates.

            ## Changes
            - Reflected the latest version of OpenAPI specifications
            - Regenerated SDK code
            - Code formatting with Biome

            ## Review checklist
            - [ ] Check if breaking changes are included
            - [ ] Determine if version update (Major/Minor/Patch) is needed
          branch: feat/update-sdk
          delete-branch: true
          labels: |
            sdk-update
            automated-pr